# Generated by Django 3.0.3 on 2020-02-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('local_phone', models.CharField(max_length=64)),
                ('mobile_phone', models.CharField(max_length=64)),
                ('duties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='duties.Duty')),
            ],
        ),
    ]
