# Generated by Django 3.0.3 on 2020-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='long_name',
        ),
        migrations.AddField(
            model_name='group',
            name='short_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
