# Generated by Django 3.0.3 on 2020-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_auto_20200320_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['long_name']},
        ),
        migrations.AlterField(
            model_name='dutydate',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
