# Generated by Django 3.0.3 on 2020-04-10 22:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0004_dutyperson_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyperson',
            name='color',
            field=colorfield.fields.ColorField(default='#762f96', max_length=18, unique=True),
        ),
    ]
